<!-- home-page-slider -->

<div class="homepage-slider some-block">
    <div class="homepage-slide">
            <div class="some-img">
                <img src="{{media url="wysiwyg//home/home-main.jpg"}}" alt="">
            </div>
        <span class="block-content">
            <strong class="block-title">
                Outdoor Dining
            </strong>
            <span class ="block-info">
                Get summer ready with <br> our exclusive outdoor funiture
            </span>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP OUTDOOR DAYBEDS</a>
        </span> 
    </div>
    <div class="homepage-slide">
            <div class="some-img">
                <img src="{{media url="wysiwyg/slider/Image1.png"}}" alt="">
            </div>
        <span class="block-content">
            <strong class="block-title">
                Outdoor Dining
            </strong>
            <span class ="block-info">
                Get summer ready with <br> our exclusive outdoor funiture
            </span>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP OUTDOOR DAYBEDS</a>
        </span> 
    </div>
    <div class="homepage-slide">
        <span class="block-content">
            <strong class="block-title">
                Outdoor Dining
            </strong>
            <span class ="block-info">
                Get summer ready with <br> our exclusive outdoor funiture
            </span>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP OUTDOOR DAYBEDS</a>
        </span> 
    </div>
</div>



<!-- shop-now-block -->
<div class="block-shop-now-wrapper row"> 
    <div class="block-shop-now  some-block col-mb-6"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/shop-now/Image1.png"}}" alt="">
        </div>
        <span class="block-content">
            <strong class="block-title">
                OUTDOOR DINING
            </strong>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP NOW</a>
        </span> 
    </div>
    <div class="block-shop-now  some-block col-mb-6"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/shop-now/Image2.png"}}" alt="">
        </div>
        <span class="block-content">
            <strong class="block-title">
                OUTDOOR LOUNGES
            </strong>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP NOW</a>
        </span> 
    </div>
</div>


<!-- reason-to-buy -->
<div class="reason-to-buy-block some-block">
    <div class="reason-to-buy">
        <a class="action more icon" href="{{store url=""}}#">OUTDOOR FUNITURE CLEARANCE STORE</a>
    </div>
    <div class="reason-to-buy">
        <a class="action more icon" href="{{store url=""}}#">WE SHIP AUSTRALIA WIDE</a>
    </div>
    <div class="reason-to-buy">
        <a class="action more icon" href="{{store url=""}}#">30 DAY MONEY BACK GUARANTEE</a>
    </div>

</div>



<!-- block-banner -->
<div class="block-banner-wrapper row">
    <div class="block-banner some-block col-mb-4"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/block-banner/Image1.png"}}" alt="">
        </div>
        <div class="block-content-expansion">
            <span class="block-content">
                <strong class="block-title">
                    Vogue Collection
                </strong>
                <span class ="block-info">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.
                </span>
                <a class="action shop-btn more icon">SHOP NOW</a>
            </span> 
        </div>
    </div>
    <div class="block-banner some-block col-mb-4"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/block-banner/Image2.png"}}" alt="">
        </div>
        <div class="block-content-expansion">
            <span class="block-content">
                <strong class="block-title">
                    Maldives Collection
                </strong>
                <span class ="block-info">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.
                </span>
                <a class="action shop-btn more icon">SHOP NOW</a>
            </span> 
        </div>
    </div>
    <div class="block-banner some-block col-mb-4"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/block-banner/Image3.png"}}" alt="">
        </div>
        <div class="block-content-expansion">
            <span class="block-content">
                <strong class="block-title">
                    Marseilles Collection
                </strong>
                <span class ="block-info">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.
                </span>
                <a class="action shop-btn more icon">SHOP NOW</a>
            </span> 
        </div>
    </div>
</div>


<div class="video-block-slider">
    <div class="video-block some-block"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/video/Image1.png"}}" alt="">
        </div>
        <span class="block-content">
            <strong class="block-title">
                CATALOGUES
            </strong>
            <a class="action shop-btn more icon" href="{{store url=""}}#">EXPLORE NOW</a>
        </span> 
    </div> 
    <div class="video-block some-block"> 
        <div class="some-img">
            <img src="{{media url="wysiwyg/video/Image1.png"}}" alt="">
        </div>
        <div class="some-video">
            <iframe width="100%" height="100%" src="https://www.youtube.com/embed/L5cgVAItXgc?autoplay=1" frameborder="0" allowfullscreen="allowfullscreen">
            </iframe>
        </div>
    </div> 
</div>