
    <!-- ***************************************slider********************* -->

<div class="style-guide-slider some-block">
    <div class="style-guide-slide">
        <img src="{{media url="wysiwyg//home/home-main.jpg"}}" alt="">
        <span class="block-content">
            <strong class="block-title">
                Outdoor Dining
            </strong>
            <span class ="block-info">
                Get summer ready with <br> our exclusive outdoor funiture
            </span>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP OUTDOOR DAYBEDS</a>
        </span> 
    </div>
    <div class="style-guide-slide">

        <span class="block-content">
            <strong class="block-title">
                Outdoor Dining
            </strong>
            <span class ="block-info">
                Get summer ready with <br> our exclusive outdoor funiture
            </span>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP OUTDOOR DAYBEDS</a>
        </span> 
    </div>
</div>



<!-- shop now block -->
<div class="style-guide-block-shop-now some-block row"> 
    <div class="style-guide-block col-6"> 
        <img src="{{media url="wysiwyg/shop-now/Image1.png"}}" alt="">
        <span class="block-content">
            <strong class="block-title">
                OUTDOOR DINING
            </strong>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP NOW</a>
        </span> 
    </div>
    <div class="style-guide-block col-6"> 
        <img src="{{media url="wysiwyg/shop-now/Image2.png"}}" alt="">
        <span class="block-content">
            <strong class="block-title">
                OUTDOOR LOUNGES
            </strong>
            <a class="action shop-btn more icon" href="{{store url=""}}#">SHOP NOW</a>
        </span> 
    </div>
</div>


<!-- reason to buy -->
<div class="reason-to-buy-block some-block row">
    <div class="reason-to-buy col-4">
        <a class="action more icon" href="{{store url=""}}#">OUTDOOR FUNITURE CLEARANCE STORE</a>
    </div>
    <div class="reason-to-buy col-4">
        <a class="action more icon" href="{{store url=""}}#">WE SHIP AUSTRALIA WIDE</a>
    </div>
    <div class="reason-to-buy col-4">
        <a class="action more icon" href="{{store url=""}}#">30 DAY MONEY BACK GUARANTEE</a>
    </div>

</div>