<!-- Session Our Blog -->
<!-- <div class="session-our-blog some-block">
    <div class="heading">
        <h1>Lifestyle Blog</h1>
    </div>
    <div class="our-blog-main">
        <div class="row">
            <div class="col-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog1.jpg"}}" alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>Add a burst of colour to your backyard</h3>
                        <div class="content style-guide-paragraph">
                            <p>Introducing the Sunbrella ottoman collection, an exciting set of new outdoor accessory pieces that will liven up any outdoor lounge setting...</p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog2.jpg"}}" alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>The Maldives modular collection</h3>
                        <div class="content style-guide-paragraph">
                            <p>Outdoor modular lounges are enjoying extraordinary popularity at the moment as we look to bring the comforts of the lounge room into the great outdoors...</p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog3.jpg"}}" alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>Outdoor furniture trends - this years hottest wicker colour</h3>
                        <div class="content style-guide-paragraph">
                            <p>After launching the colour last year we are finding our "Moonscape" synthetic wicker colour extraordinarily popular. It really has given all weather wicker outdoor furniture...</p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog4.png"}}" alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>Is this the best outdoor table in Australia?</h3>
                        <div class="content style-guide-paragraph">
                            <p>When it comes to furniture materials suitable for extended life in the Australian outdoors it is hard to go past aluminium. It is very light and will not rust which makes...</p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog5.jpg"}}" alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>The undeniable elegance of cast aluminum furniture</h3>
                        <div class="content style-guide-paragraph">
                            <p>Having used cast aluminium outdoor furniture for years in our dining range we are still unsure if it's growing popularity is due more to its elegant look or the superb performance qualities...</p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog6.jpg"}}" alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>Christmas decorating for your outdoor setting</h3>
                        <div class="content style-guide-paragraph">
                            <p>When decorating for Christmas, many people remember to decorate the house, the yard and the Christmas tree but what about the dining room table? </p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> -->
<!-- End Session Our Blog -->

<!-- test cms -->
<?php

echo $block->getLayout()

    ->createBlock('Magento\Cms\Block\Block')

    ->setBlockId('our-blog')

    ->toHtml();

?>
<!-- end test cms -->

<!-- Session Burning Log Testimonials -->
<!-- <div class="session-testimonials">
    <div class="heading">
        <h1>Burning Log Testimonials</h1>
    </div>
    <div class="testimonials-review">
        <div class="row">
            <div class="col-6">
                <div class="testimonials-container">
                    <div class="content-comment">
                        <div class="content style-guide-paragraph">
                            <p>We just had our outdoor seating delivered. A massive thank you to Tony (Melbourne store) for your service. You went above and beyond, and you always...</p>
                        </div>
                    </div>
                    <div class="testimonials-renderer">
                        <h4>Rebecca</h4>
                        <div class="date-comment style-guide-paragraph">
                            <p>November 17,2016</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="testimonials-container">
                    <div class="content-comment">
                        <div class="content style-guide-paragraph">
                            <p>We just had our outdoor seating delivered. A massive thank you to Tony (Melbourne store) for your service. You went above and beyond, and you always...<a class="content-link web-link" href="#">View more</a></p>
                        </div>
                    </div>
                    <div class="testimonials-renderer">
                        <h4>Rebecca</h4>
                        <div class="date-comment style-guide-paragraph">
                            <p>November 17,2016</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="testimonials-container">
                    <div class="content-comment">
                        <div class="content style-guide-paragraph">
                            <p>We have purchased an outdoor lounge from Outdoor Elegance and just wanted to say the experience was fantastic from the purchase to the delivery...<a class="content-link web-link" href="#">View more</a></p>
                        </div>
                    </div>
                    <div class="testimonials-renderer">
                        <h4>Michelle</h4>
                        <div class="date-comment style-guide-paragraph">
                            <p>November 29,2016</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="testimonials-container">
                    <div class="content-comment">
                        <div class="content style-guide-paragraph">
                            <p>Excellent service from Tamara at Terrey Hills. Lyon table and Maldives chairs arrived on Monday, couldn't be...<a class="content-link web-link" href="#">View more</a></p>
                        </div>
                    </div>
                    <div class="testimonials-renderer">
                        <h4>Michelle</h4>
                        <div class="date-comment style-guide-paragraph">
                            <p>November 29,2016</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="testimonials-review-link">
            <a class="action secondary" href="#">View more testimonials</a>
        </div>
    </div>
</div> -->
<!-- End Session Burning Log Testimonials -->

<!-- Session test Burning Log Testimonials -->
<?php
echo $block->getLayout()

    ->createBlock('Magento\Cms\Block\Block')

    ->setBlockId('burning-log-testimonials')

    ->toHtml();
?>
<!-- End test Session Burning Log Testimonials -->

<!-- Showrom -->
<div class="session-showrom">
    <div class="row">
        <div class="col-4">
            <div class="showrom-img some-img">
                <img src="{{media url="wysiwyg/image_showroom_footer/outdoor_Elegance.png"}}"
                    alt="Outdoor Elegance Logo">
            </div>
        </div>
        <div class="col-4">
            <div class="showrom-Canberra"><a class="Canberra-link action secondary" href="#">Canberra Showroom</a>
                <div class="style-guide-paragraph">
                    <p>Maryborough St &amp; Wollongong Street, Fyshwick ACT 2609 T: 1300 6</p>
                </div>
                <a class="web-link links-info" href="#">Text link</a>
            </div>
        </div>
        <div class="col-4">
            <div class="showrom-img some-img">
                <img src="{{media url="wysiwyg/image_showroom_footer/webstore_logo.png"}}" alt="Web Store Logo">
            </div>
        </div>
    </div>
</div>
<!-- End showrom -->