<!-- Session Our Blog -->
<div class="session-our-blog some-block">
    <div class="my-content-heading some-block">
        <h1 class="title">Lifestyle Blog</h1>
    </div>
    <div class="our-blog-main">
        <div class="row">
            <div class="col-mb-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog1.jpg"}}"
                            alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>Add a burst of colour to your backyard</h3>
                        <div class="content style-guide-paragraph">
                            <p>Introducing the Sunbrella ottoman collection, an exciting set of new outdoor accessory
                                pieces that will liven up any outdoor lounge setting...</p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
            <div class="col-mb-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog2.jpg"}}"
                            alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>The Maldives modular collection</h3>
                        <div class="content style-guide-paragraph">
                            <p>Outdoor modular lounges are enjoying extraordinary popularity at the moment as we look to
                                bring the comforts of the lounge room into the great outdoors...</p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
            <div class="col-mb-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog3.jpg"}}"
                            alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>Outdoor furniture trends - this years hottest wicker colour</h3>
                        <div class="content style-guide-paragraph">
                            <p>After launching the colour last year we are finding our "Moonscape" synthetic wicker
                                colour extraordinarily popular. It really has given all weather wicker outdoor
                                furniture...</p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
            <div class="col-mb-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog4.png"}}"
                            alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>Is this the best outdoor table in Australia?</h3>
                        <div class="content style-guide-paragraph">
                            <p>When it comes to furniture materials suitable for extended life in the Australian
                                outdoors it is hard to go past aluminium. It is very light and will not rust which
                                makes...</p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
            <div class="col-mb-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog5.jpg"}}"
                            alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>The undeniable elegance of cast aluminum furniture</h3>
                        <div class="content style-guide-paragraph">
                            <p>Having used cast aluminium outdoor furniture for years in our dining range we are still
                                unsure if it's growing popularity is due more to its elegant look or the superb
                                performance qualities...</p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
            <div class="col-mb-4">
                <div class="our-blog-container">
                    <div class="our-blog-image some-img">
                        <img src="{{media url="wysiwyg/image_our_blog/image_our_blog6.jpg"}}"
                            alt="Image Lifestyle Blog">
                    </div>
                    <div class="our-blog-content">
                        <h3>Christmas decorating for your outdoor setting</h3>
                        <div class="content style-guide-paragraph">
                            <p>When decorating for Christmas, many people remember to decorate the house, the yard and
                                the Christmas tree but what about the dining room table? </p>
                        </div>
                    </div>
                    <div class="our-blog-link">
                        <a class="web-link" href="#">View more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Session Our Blog -->

<!-- test cms -->
<?php

echo $block->getLayout()

    ->createBlock('Magento\Cms\Block\Block')

    ->setBlockId('our-blog')

    ->toHtml();

?>
<!-- end test cms -->

<!-- Session Burning Log Testimonials -->
<div class="session-testimonials">
    <div class="heading">
        <h1>Burning Log Testimonials</h1>
    </div>
    <div class="testimonials-review">
        <div class="row">
            <div class="col-mb-6">
                <div class="testimonials-container">
                    <div class="content-comment">
                        <div class="content style-guide-paragraph">
                            <p>We just had our outdoor seating delivered. A massive thank you to Tony (Melbourne store)
                                for your service. You went above and beyond, and you always...</p>
                        </div>
                    </div>
                    <div class="testimonials-renderer">
                        <h4>Rebecca</h4>
                        <div class="date-comment style-guide-paragraph">
                            <p>November 17,2016</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-mb-6">
                <div class="testimonials-container">
                    <div class="content-comment">
                        <div class="content style-guide-paragraph">
                            <p>We just had our outdoor seating delivered. A massive thank you to Tony (Melbourne store)
                                for your service. You went above and beyond, and you always...<a
                                    class="content-link web-link" href="#">View more</a></p>
                        </div>
                    </div>
                    <div class="testimonials-renderer">
                        <h4>Rebecca</h4>
                        <div class="date-comment style-guide-paragraph">
                            <p>November 17,2016</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-mb-6">
                <div class="testimonials-container">
                    <div class="content-comment">
                        <div class="content style-guide-paragraph">
                            <p>We have purchased an outdoor lounge from Outdoor Elegance and just wanted to say the
                                experience was fantastic from the purchase to the delivery...<a
                                    class="content-link web-link" href="#">View more</a></p>
                        </div>
                    </div>
                    <div class="testimonials-renderer">
                        <h4>Michelle</h4>
                        <div class="date-comment style-guide-paragraph">
                            <p>November 29,2016</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-mb-6">
                <div class="testimonials-container">
                    <div class="content-comment">
                        <div class="content style-guide-paragraph">
                            <p>Excellent service from Tamara at Terrey Hills. Lyon table and Maldives chairs arrived on
                                Monday, couldn't be...<a class="content-link web-link" href="#">View more</a></p>
                        </div>
                    </div>
                    <div class="testimonials-renderer">
                        <h4>Michelle</h4>
                        <div class="date-comment style-guide-paragraph">
                            <p>November 29,2016</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="testimonials-review-link">
            <a class="action secondary" href="#">View more testimonials</a>
        </div>
    </div>
</div>
<!-- End Session Burning Log Testimonials -->

<!-- Session test Burning Log Testimonials -->
<?php
echo $block->getLayout()

    ->createBlock('Magento\Cms\Block\Block')

    ->setBlockId('burning-log-testimonials')

    ->toHtml();
?>
<!-- End test Session Burning Log Testimonials -->

<!-- footer -->

<!-- Showrom -->
<div class="session-showrom">
    <div class="row">
        <div class="col-mb-4">
            <div class="showrom-img some-img"><img
                    src="{{media url="wysiwyg/image_showroom_footer/outdoor_Elegance.png"}}"
                    alt="Outdoor Elegance Logo"></div>
        </div>
        <div class="col-mb-4">
            <div class="showrom-Canberra"><a class="canberra-link action secondary" href="#">Canberra Showroom</a>
                <div class="style-guide-paragraph">
                    <p>Maryborough St &amp; Wollongong Street, Fyshwick ACT 2609 T: 1300 6</p>
                </div>
                <a class="web-link links-info" href="#">Text link</a>
            </div>
        </div>
        <div class="col-mb-4">
            <div class="showrom-img some-img"><img src="{{media url="wysiwyg/image_showroom_footer/webstore_logo.png"}}"
                    alt="Web Store Logo"></div>
        </div>
    </div>
</div>
<!-- End showrom -->

<!-- Footer banner-->
<div class="session-footer-banner">
    <div class="backgroud-color">
        <div class="footer-banner backgroud-img"
            style="background-image: url('{{media url="wysiwyg/image_backgroud_footer/backgroud-banner-min.png"}}');">
            <div class="content-banner">
                <h1 class="title-banner">Exclusive outdoor furniture, online prices</h1>
                <div class="style-guide-paragraph">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore
                        et dolore magna aliqua.
                    </p>
                    <a class="web-link links-banner" href="#">View more infor</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End footer banner-->

<!-- footer top -->
<div class="footer-top">
    <div class="row">
        <div class="col-mb-3">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-truck">&nbsp;</i>
                </div>
                <span class="text">We ship australia wide!</span>
            </div>
        </div>
        <div class="col-mb-3">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-location-dot">&nbsp;</i>
                </div>
                <span class="text">Find a store</span>
            </div>
        </div>
        <div class="col-mb-3">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-dollar-sign">&nbsp;</i>
                </div>
                <span class="text">Money back guarantee</span>
            </div>
        </div>
        <div class="col-mb-3">
            <div class="footer-top-item">
                <div class="icon">
                    <i class="fa-solid fa-envelope">&nbsp;</i>
                </div>
                <span class="text">Contact us</span>
            </div>
        </div>
    </div>
</div>
<!-- end footer top -->

<!-- Footer links desktop-->
<div class="footer-links-desktop">
    <div class="row">
        <div class="col-mb-4">
            <div class="footer-links">
                <h3>Category</h3>
                <ul class="nav-link">
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-mb-4">
            <div class="footer-links">
                <h3>Why Burning Log?</h3>
                <ul class="nav-link">
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-mb-4">
            <div class="footer-links">
                <h3>Out Policies</h3>
                <ul class="nav-link">
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                    <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- end Footer links desktop-->

<!-- Newletter-->
<div class="footer-links-newsletter">
    <h3>Newsletter</h3>
    <ul>
        <li><a>Subscribe to our newsletter for the latest news and updates</a></li>
    </ul>
</div>
<!-- End Newletter-->

<!-- nav icon -->
<div class="nav-footer-icon">
    <div class="icon-item">
        <div class="social-icon"><a href="#"><i class="fab fa-facebook-f">&nbsp;</i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-instagram">&nbsp;</i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-twitter">&nbsp;</i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-brands fa-youtube">&nbsp;</i></a></div>
        <div class="social-icon"><a href="#"><i class="fab fa-brands fa-pinterest">&nbsp;</i></a></div>
    </div>
</div>
<!-- end nav icon -->

<!-- Footer links mobile-->
<div class="footer-links-mobile" id="accordion" data-mage-init='{
        "accordion":{
            "active": [0],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
    <div data-role="collapsible">
        <div data-role="trigger"> <span class="minus"><i class="fa-solid fa-xmark">&nbsp;</i></span><span
                class="plus"><i class="fa-solid fa-plus">&nbsp;</i></span></h3>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
            </li>
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}
            </li>
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}
            </li>
        </ul>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">ning Log? <span class="minus"><i class="fa-solid fa-xmark">&nbsp;</i></span><span
                class="plus"><i class="fa-solid fa-plus">&nbsp;</i></span></h3>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Lounges" title="Outdoor Lounges" template="category/widget/link/link_block.phtml" id_path="category/20"}}
            </li>
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Dining" title="Outdoor Dining" template="category/widget/link/link_block.phtml" id_path="category/11"}}
            </li>
            <li>{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="Outdoor Umbrellas &amp; Accessories " title="Outdoor Umbrellas &amp; Accessories " template="category/widget/link/link_block.phtml" id_path="category/11"}}
            </li>
        </ul>
    </div>
    <div data-role="collapsible">
        <div data-role="trigger">icies <span class="minus"><i class="fa-solid fa-xmark">&nbsp;</i></span><span
                class="plus"><i class="fa-solid fa-plus">&nbsp;</i></span></h3>
        </div>
    </div>
    <div data-role="content">
        <ul class="nav-link">
            <li><a>Subscribe to our newsletter for the latest news and updates</a></li>
        </ul>
    </div>
</div>
<!-- End Footer links mobile-->

<!-- img logo footer -->
<div class="logo-footer">
    <div class="img-item"><img src="{{media url="wysiwyg/image_logo_footer/Layer_572.png"}}" alt=""></div>
    <div class="img-item"><img src="{{media url="wysiwyg/image_logo_footer/PayPal.jpg"}}" alt=""></div>
    <div class="img-item"><img src="{{media url="wysiwyg/image_logo_footer/Visa.png"}}" alt=""></div>
    <div class="img-item"><img src="{{media url="wysiwyg/image_logo_footer/Mastercard.png"}}" alt=""></div>
    <div class="img-item"><img src="{{media url="wysiwyg/image_logo_footer/American-express.png"}}" alt=""></div>
</div>
<!-- end img logo footer -->