<!-- numberbutton -->
<script type="text/javascript">
    // This is the javascript codes help us to increase and decrease qty
    require([
        'jquery'
    ], function($) {
        $(document).on('click', '.add-qty-button', function() {
            let abc = $(this).closest('.number-input-form-qty').find('input');
            abc.val(parseInt(abc.val()) + 1);
            if(abc.val()>100){
                abc.val(100);
            }
        });
        $(document).on('click', '.minus-qty-button', function() {
            let abc = $(this).closest('.number-input-form-qty').find('input');
            abc.val(parseInt(abc.val()) - 1);
            if(abc.val()<1){
                abc.val(1);
            }
        });
    });
    
</script>

<!--**************** slick******************* -->
<!-- homepage banner slick -->

<script>
    require([
        'jquery',
        'slick',
        'domReady!'
    ], function ($) {
        $(".homepage-slider").slick({
            dots: false,
            infinite: true,
            speed: 300,
            slidesToShow: 1,
            slidesToScroll: 1,
            arrows: false,
            autoplay: true,
            autoplaySpeed: 5000,
            mobileFirst: true
        });
        $('.reason-to-buy-block').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            dots: false,
            infinite: true,
            speed: 300,
            arrows: false,
            autoplay: true,
            autoplaySpeed: 5000,
            
            mobileFirst: true,
            responsive: [
                {
                    breakpoint: 1280,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 1,
                        dots: false,
                        infinite: false,
                        speed: 300,
                        arrows: false,
                        autoplay: false,
                        autoplaySpeed: 5000,
                    }
                }
            ]
        });
        $('.video-block-slider').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            dots: false,
            infinite: true,
            speed: 300,
            arrows: false,
            autoplay: true,
            autoplaySpeed: 5000,
            centerPadding: '20px',
            mobileFirst: true,
            responsive: [
                {
                    breakpoint: 1280,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 1,
                        dots: false,
                        infinite: false,
                        speed: 300,
                        arrows: false,
                        autoplay: false,
                        autoplaySpeed: 5000,
                        centerPadding: '20px',
                        
                    }
                }
            ]
        });
        $(".widget-product-slick").slick({
            rows: 1,
            dots: false,
            infinite: false,
            speed: 300,
            slidesToShow: 4,
            slidesToScroll: 1,
            arrows: true,
            responsive: [
                {
                    breakpoint: 1280,
                    settings: {
                        dots: false,
                        infinite: false,
                        speed: 300,
                        slidesToShow: 2,
                        slidesToScroll: 1,
                        arrows: false,
                    }
                },
            ]
        });
    });
</script>


