<div class="header-pc">
    <div class="header-contact">
        Contactus  /  <a href="">1300 660 330</a>
    </div>
    <div class="header-info">
        <ul>
            <li><a href="">Outdor Furniture</a></li>
            <li><a href="">Fireplaces</a></li>
            <li><a href="">Weber BBQs</a></li>
            <li><a href="">Canberra Showroom Open 7 Days</a></li>
        </ul>
    </div>
    <div class="header-more">
        <ul>
            <li><a href=""><i class="fa-brands fa-facebook-f"></i></a></li>
            <li><a href=""><i class="fa-brands fa-instagram"></i></a></li>
            <li><a href="">Blog</a></li>
            <li><a href="">Login</a></li>
        </ul>
    </div>
</div>


<div class="header-mobile" style="display: none;">
    <div class="header-contact">
        Contactus / <a href="">1300 660 330</a>
    </div>
    <div class="header-info">
        <ul>
            <li><a href="">Outdor Furniture</a></li>
            <li><a href="">Fireplaces</a></li>
            <li><a href="">Weber BBQs</a></li>
            <li><a href="">Canberra Showroom Open 7 Days</a></li>
        </ul>
    </div>
    <div class="header-more">
        <ul>
            <li><a href=""><i class="fa-brands fa-facebook-f"></i></a></li>
            <li><a href=""><i class="fa-brands fa-instagram"></i></a></li>
            <li><a href="">blog</a></li>
            <li><a href="">login</a></li>
        </ul>
    </div>
</div>